### ISSUE TITLE
Добавить api для изменения локации юзера + поправить поле локация

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/phoqer#148]
Нужна апи которая будет менять только поле локации у юзера и еще нужно поправить это же поле у юзера так как сейчас это просто строка а там скорее всего должен быть объект со страной и городом

**Comment by iMykhailychenko** [comment]
и убрать слеш в конце
<img width="526" alt="Снимок экрана 2021-05-09 в 19 38 26" src="https://user-images.githubusercontent.com/50461642/117579978-34dccf00-b0fe-11eb-81f4-7a93f0a50158.png">

**Comment by MarianMalvin** [comment]
я тут просто сделаю апи для изменения информации пользователя, что бы partial update по одному полю локализация
