### ISSUE TITLE
Снести джанговские таблици

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/phoqer#152]
<img width="412" alt="Снимок экрана 2021-05-11 в 11 44 41" src="https://user-images.githubusercontent.com/50461642/117789493-13402c80-b251-11eb-855c-05f3a5a68984.png">

**Comment by EgorFray** [comment]
Снёс всё нахрен. Если что - бекап сделал

**Comment by MarianMalvin** [comment]
users_user_user_permissions
users_user_user_groups
и все что начинается с auth_*

**Comment by EgorFray** [comment]
Всё снёс, абсолютно
