### ISSUE TITLE
Поменять ссылки на соцсети

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/phoqer#153]
<img width="298" alt="Снимок экрана 2021-05-11 в 12 08 38" src="https://user-images.githubusercontent.com/50461642/117790031-a11c1780-b251-11eb-8dc2-872653734f72.png">

Поставить сюда адекватные ссылки. Уточни у Марьяна, он там что-то создавал

**Comment by EgorFray** [comment]
Нужно ещё вставить ссылку на твитер, потому что его ещё не создали
