### ISSUE TITLE
Поменять фотки категорий в базе данных

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/phoqer#156]
Вот и настало время тебе окунуться в мир бекенда, хоть и не сильно глубоко, буквально по щиколотки, но тем не менее. 
Проблема в том, что картинки на наших категориях слишком большие и медленно грузятся, нужно заменить их на такие же но меньшего размера, примерно 640 на 360. Нужно зайти на этот сайт https://unsplash.com/ и найти там такие же картинки, как и у нас сейчас на категориях. В крайнем случае похожие картинки взять.

Потом нужно зайти в нашу админку от postgres, применить все свое мастерство гуглить sql запросы для изменения таблиц в бд и поменять существующие ссылки на те, что ты нашел.

**Comment by EgorFray** [comment]
Всё готово
