### ISSUE TITLE
Что нужно поправить в форме создания товара?

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/phoqer#157]
У нас было куча изменений в логике (в частности валюта добавилась) и сейчас форма создания товара не добавляет всю нужную информацию. Нужно подумать какие еще поля добавить (валюта/период аренды/количество товара)

**Comment by MarianMalvin** [comment]
четыре валюты: доллары, евро, гривны, русские рубли

**Comment by MarianMalvin** [comment]
результат нашего анала #162
