### ISSUE TITLE
Поправить валидацию при изменении статуса товара

### ISSUE THREAD

**Issue by iMykhailychenko** [MarianMalvin/phoqer#159]
<img width="700" alt="Screenshot 2021-05-15 at 19 54 55" src="https://user-images.githubusercontent.com/50461642/118371944-9fd34d80-b5b7-11eb-8434-62cdba8bb521.png">
<img width="710" alt="Screenshot 2021-05-15 at 19 55 01" src="https://user-images.githubusercontent.com/50461642/118371946-a1047a80-b5b7-11eb-8241-cbf37e239c85.png">

Мы решили, что cover_image пока будет не обязательным полем

**Comment by iMykhailychenko** [comment]
и deposit_val тоже по сути не обязательно

**Comment by MarianMalvin** [comment]
- [ ] поченить это asyncpg.exceptions.DataError: invalid input for query argument $2: <Status.ACTIVE: 'ACTIVE'> (expected str, got Status)
- [ ] переназвать фенкцию edit для разных статусов. edit для офера в статусе draft и edit для очера в статусе active
