### ISSUE TITLE
убрать ТОП объявления с поиска

### ISSUE THREAD

**Issue by MarianMalvin** [MarianMalvin/phoqer#167]
ТОП объявления не релевантны к поиску, так что пока-что уберем их

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/22667729/119560880-c5750980-bda4-11eb-90ff-f08b3df215ab.png">

**Comment by MarianMalvin** [comment]
Батя всея фронтенда сказал, что-бы ты не удалял этого, а просто закомментировал

**Comment by Anndersonn** [comment]
Та я, вроде, ничего не говорил. Кек
